package com.stevesuzon.carlplay;

import android.Manifest;import android.annotation.SuppressLint;import android.app.Activity;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.net.*;import android.net.Uri;import android.os.Bundle;import android.os.SystemClock;import android.os.Handler;import android.os.Looper;import android.provider.Settings;import android.view.*;import android.webkit.*;import android.widget.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.Locale;import java.net.HttpURLConnection;import java.net.URL;import java.text.SimpleDateFormat;import java.util.Date;import java.io.*;

public class MainActivity extends Activity{
 static final int LOCATION_REQUEST=1001;static final long DAY=86400000L,LICENSE_DAYS=365L,GRACE_DAYS=7L;static final String PREFS="carlplay_license",SECRET="CP66-365-RENOUVELLEMENT-SUZON-2026",LIFE_SECRET="CP66-LIFETIME-CARPLAY-STEVE-2026",STATE_SECRET="CP66-STATE-CARPLAY-STEVE-2026";
 WebView webView;ConnectivityManager cm;ConnectivityManager.NetworkCallback cb;SharedPreferences prefs;TextView badge,network,clock;FrameLayout root;Handler clockHandler=new Handler(Looper.getMainLooper());
 Runnable clockTick=new Runnable(){public void run(){updateClock();clockHandler.postDelayed(this,1000);}};
 public class AndroidStatus{
  @JavascriptInterface public boolean hasInternet(){try{Network n=cm.getActiveNetwork();NetworkCapabilities c=n==null?null:cm.getNetworkCapabilities(n);return c!=null&&c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)&&c.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED);}catch(Exception e){return false;}}
  @JavascriptInterface public boolean licenseExpired(){return expired(now());}@JavascriptInterface public String licenseRequestCode(){return formatReq(requestCode());}@JavascriptInterface public String renewLicense(String code){return renew(code)?"OK":"ERREUR";}@JavascriptInterface public long licenseDaysLeft(){return isLifetime()?999999L:daysLeft(now());}@JavascriptInterface public boolean licenseLifetime(){return isLifetime();}
 }
 boolean isLifetime(){return prefs.getBoolean("lifetime",false);}
 String deviceId(){String id=Settings.Secure.getString(getContentResolver(),Settings.Secure.ANDROID_ID);return id==null?"unknown":id;}
 String hash(String v){try{MessageDigest m=MessageDigest.getInstance("SHA-256");byte[] b=m.digest(v.getBytes(StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.US,"%02x",x&255));return s.toString();}catch(Exception e){return"0000000000000000";}}
 String deviceKey(){return hash("CARPLAY-TRAVAILLE|"+deviceId()).substring(0,24);}
 File stateFile(){try{File[] dirs=getExternalMediaDirs();if(dirs!=null&&dirs.length>0&&dirs[0]!=null){File d=new File(dirs[0],".carplay_travaille");if(!d.exists())d.mkdirs();return new File(d,".licence_state");}}catch(Exception ignored){}return null;}
 String statePayload(long start,long last,int cycle,boolean life,long trusted){return "v1|"+deviceKey()+"|"+start+"|"+last+"|"+cycle+"|"+(life?1:0)+"|"+trusted;}
 void savePersistentState(){try{File f=stateFile();if(f==null)return;long s=prefs.getLong("license_start",0L),l=prefs.getLong("last_seen",0L),t=prefs.getLong("trusted_epoch",0L);int c=prefs.getInt("renewal_cycle",0);boolean life=prefs.getBoolean("lifetime",false);String p=statePayload(s,l,c,life,t),sig=hash(STATE_SECRET+"|"+p);File tmp=new File(f.getParentFile(),f.getName()+".tmp");try(FileOutputStream out=new FileOutputStream(tmp)){out.write((p+"|"+sig).getBytes(StandardCharsets.UTF_8));out.flush();}if(f.exists())f.delete();tmp.renameTo(f);}catch(Exception ignored){}}
 void restorePersistentState(){try{File f=stateFile();if(f==null||!f.exists())return;byte[] b=new byte[(int)Math.min(f.length(),4096)];int n;try(FileInputStream in=new FileInputStream(f)){n=in.read(b);}if(n<=0)return;String s=new String(b,0,n,StandardCharsets.UTF_8).trim();String[] a=s.split("\\|");if(a.length!=8||!"v1".equals(a[0])||!deviceKey().equals(a[1]))return;String p=String.join("|",java.util.Arrays.copyOfRange(a,0,7));if(!hash(STATE_SECRET+"|"+p).equals(a[7]))return;long ps=Long.parseLong(a[2]),pl=Long.parseLong(a[3]),pt=Long.parseLong(a[6]);int pc=Integer.parseInt(a[4]);boolean life="1".equals(a[5]);long cs=prefs.getLong("license_start",0L),cl=prefs.getLong("last_seen",0L),ct=prefs.getLong("trusted_epoch",0L);int cc=prefs.getInt("renewal_cycle",0);SharedPreferences.Editor ed=prefs.edit();if(ps>0&&(cs==0L||ps<cs))ed.putLong("license_start",ps);if(pl>cl)ed.putLong("last_seen",pl);if(pt>ct)ed.putLong("trusted_epoch",pt);if(pc>cc)ed.putInt("renewal_cycle",pc);if(life)ed.putBoolean("lifetime",true);ed.apply();}catch(Exception ignored){}}
 long trustedClock(){long epoch=prefs.getLong("trusted_epoch",0L),elapsed=prefs.getLong("trusted_elapsed",0L);if(epoch<=0||elapsed<=0)return 0L;long d=SystemClock.elapsedRealtime()-elapsed;return d>=0?epoch+d:epoch;}
 long displayClockMillis(){long system=System.currentTimeMillis();long off=prefs.getLong("internet_offset",Long.MIN_VALUE);if(off!=Long.MIN_VALUE)return system+off;long trusted=trustedClock();return trusted>0?Math.max(system,trusted):system;}
 long now(){long system=System.currentTimeMillis(),trusted=trustedClock(),last=prefs.getLong("last_seen",0L);long e=Math.max(last,Math.max(system,trusted));prefs.edit().putLong("last_seen",e).apply();savePersistentState();return e;}
 long start(){long s=prefs.getLong("license_start",0);if(s==0){long base=trustedClock();if(base<=0)base=System.currentTimeMillis();s=base;prefs.edit().putLong("license_start",s).putLong("last_seen",s).apply();savePersistentState();}return s;}
 void syncInternetTime(){new Thread(()->{HttpURLConnection c=null;try{URL u=new URL("https://www.google.com/generate_204");c=(HttpURLConnection)u.openConnection();c.setConnectTimeout(5000);c.setReadTimeout(5000);c.setUseCaches(false);c.setRequestMethod("HEAD");c.connect();long server=c.getDate();if(server>1609459200000L){long elapsed=SystemClock.elapsedRealtime();long sys=System.currentTimeMillis();long oldStart=prefs.getLong("license_start",0L);SharedPreferences.Editor ed=prefs.edit().putLong("trusted_epoch",server).putLong("trusted_elapsed",elapsed).putLong("internet_offset",server-sys).putLong("last_seen",Math.max(prefs.getLong("last_seen",0L),server));if(oldStart==0L||Math.abs(oldStart-server)>30L*DAY&&Math.abs(sys-server)>30L*DAY)ed.putLong("license_start",server);ed.apply();savePersistentState();runOnUiThread(()->{updateBadge();updateClock();});}}catch(Exception ignored){}finally{if(c!=null)c.disconnect();}}).start();}
 long daysLeft(long n){if(isLifetime())return 999999L;long e=start()+LICENSE_DAYS*DAY;return n>=e?0:(long)Math.ceil((e-n)/(double)DAY);}long graceLeft(long n){if(isLifetime())return GRACE_DAYS;long e=start()+(LICENSE_DAYS+GRACE_DAYS)*DAY;return n>=e?0:(long)Math.ceil((e-n)/(double)DAY);}boolean expired(long n){return !isLifetime()&&n>=start()+(LICENSE_DAYS+GRACE_DAYS)*DAY;}
 String requestCode(){int c=prefs.getInt("renewal_cycle",0);String h=hash(deviceId()+"|"+c+"|"+start());long n;try{n=Long.parseUnsignedLong(h.substring(0,12),16)%100000000L;}catch(Exception e){n=0;}return String.format(Locale.US,"%08d",n);}String formatReq(String s){return s.substring(0,2)+"."+s.substring(2,4)+"."+s.substring(4,6)+"."+s.substring(6,8);}String expected(){String h=hash(SECRET+"|"+requestCode());long n;try{n=Long.parseUnsignedLong(h.substring(0,12),16)%100000000L;}catch(Exception e){n=0;}return String.format(Locale.US,"%08d",n);}String expectedLifetime(){String h=hash(LIFE_SECRET+"|"+requestCode());long n;try{n=Long.parseUnsignedLong(h.substring(0,12),16)%100000000L;}catch(Exception e){n=0;}return String.format(Locale.US,"%08d",n);}
 boolean renew(String entered){String x=entered==null?"":entered.replaceAll("[^0-9]","");if(expectedLifetime().equals(x)){prefs.edit().putBoolean("lifetime",true).apply();savePersistentState();runOnUiThread(()->{updateBadge();Toast.makeText(this,"Licence activée à vie",Toast.LENGTH_LONG).show();});return true;}if(!expected().equals(x))return false;int c=prefs.getInt("renewal_cycle",0)+1;long n=now();prefs.edit().putBoolean("lifetime",false).putLong("license_start",n).putLong("last_seen",n).putInt("renewal_cycle",c).apply();savePersistentState();runOnUiThread(()->{updateBadge();Toast.makeText(this,"Abonnement renouvelé pour 365 jours",Toast.LENGTH_LONG).show();});return true;}
 void updateBadge(){if(badge==null)return;if(isLifetime()){badge.setText("LICENCE  •  À VIE");badge.setBackgroundColor(Color.argb(210,16,110,62));updateNetwork();return;}long n=now(),d=daysLeft(n);if(d>0){badge.setText("LICENCE  •  "+d+" JOURS RESTANTS");badge.setBackgroundColor(Color.argb(210,5,72,120));}else if(!expired(n)){badge.setText("GRÂCE  •  "+graceLeft(n)+" JOURS  •  CONTACTEZ POUR RENOUVELER");badge.setBackgroundColor(Color.argb(225,170,95,0));}else{badge.setText("ABONNEMENT EXPIRÉ");badge.setBackgroundColor(Color.argb(235,150,20,20));}updateNetwork();}
 void updateNetwork(){if(network==null)return;boolean ok=new AndroidStatus().hasInternet();network.setText(ok?"📶 CONNECTÉ":"📶 DÉCONNECTÉ");network.setTextColor(ok?Color.rgb(65,230,105):Color.rgb(255,75,75));network.setBackgroundColor(Color.argb(190,5,10,18));}
 void updateClock(){if(clock==null)return;try{SimpleDateFormat f=new SimpleDateFormat("HH:mm",Locale.FRANCE);clock.setText(f.format(new Date(displayClockMillis())));}catch(Exception e){clock.setText("--:--");}}
 void makeTop(){int den=(int)getResources().getDisplayMetrics().density;int h=12*den,v=7*den,m=8*den;LinearLayout left=new LinearLayout(this);left.setOrientation(LinearLayout.HORIZONTAL);left.setGravity(Gravity.CENTER_VERTICAL);badge=new TextView(this);badge.setTextColor(Color.WHITE);badge.setTextSize(14);badge.setTypeface(Typeface.DEFAULT_BOLD);badge.setGravity(Gravity.CENTER_VERTICAL);badge.setPadding(h,v,h,v);left.addView(badge,new LinearLayout.LayoutParams(-2,-2));network=new TextView(this);network.setTextSize(12);network.setTypeface(Typeface.DEFAULT_BOLD);network.setGravity(Gravity.CENTER);network.setPadding(10*den,v,10*den,v);LinearLayout.LayoutParams nlp=new LinearLayout.LayoutParams(-2,-2);nlp.setMargins(6*den,0,0,0);left.addView(network,nlp);network.setOnClickListener(x->{try{startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS));}catch(Exception e){startActivity(new Intent(Settings.ACTION_SETTINGS));}});FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.LEFT);lp.setMargins(m,m,m,m);root.addView(left,lp);clock=new TextView(this);clock.setTextColor(Color.WHITE);clock.setTextSize(30);clock.setTypeface(Typeface.DEFAULT_BOLD);clock.setGravity(Gravity.CENTER);clock.setPadding(18*den,4*den,18*den,4*den);clock.setBackgroundColor(Color.argb(165,0,0,0));FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.CENTER_HORIZONTAL);cp.setMargins(0,4*den,0,0);root.addView(clock,cp);updateClock();updateNetwork();}
 void notifyNet(){runOnUiThread(()->updateNetwork());if(webView!=null)webView.post(()->webView.evaluateJavascript("if(window.updateNetworkStatus)window.updateNetworkStatus();",null));}
 void injectUi(WebView v){v.evaluateJavascript("(function(){var s=document.createElement('script');s.src='license-ui.js?'+Date.now();document.head.appendChild(s)})()",null);}
 @SuppressLint({"SetJavaScriptEnabled","AllowFileAccessFromFileURLs"}) public void onCreate(Bundle b){super.onCreate(b);getWindow().getDecorView().setSystemUiVisibility(5894);prefs=getSharedPreferences(PREFS,MODE_PRIVATE);restorePersistentState();start();savePersistentState();cm=(ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);root=new FrameLayout(this);webView=new WebView(this);root.addView(webView,new FrameLayout.LayoutParams(-1,-1));makeTop();setContentView(root);clockHandler.post(clockTick);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setGeolocationEnabled(true);s.setUseWideViewPort(true);s.setLoadWithOverviewMode(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setAllowFileAccessFromFileURLs(true);s.setAllowUniversalAccessFromFileURLs(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_ALWAYS_ALLOW);webView.addJavascriptInterface(new AndroidStatus(),"AndroidStatus");webView.setWebChromeClient(new WebChromeClient(){public void onGeolocationPermissionsShowPrompt(String o,GeolocationPermissions.Callback c){c.invoke(o,true,false);}});webView.setWebViewClient(new WebViewClient(){boolean h(String u){if(u==null||u.startsWith("file:")||u.startsWith("about:"))return false;try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){}return true;}public boolean shouldOverrideUrlLoading(WebView v,String u){return h(u);}public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return h(r.getUrl().toString());}public void onPageFinished(WebView v,String u){super.onPageFinished(v,u);injectUi(v);}});if(checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},LOCATION_REQUEST);cb=new ConnectivityManager.NetworkCallback(){public void onAvailable(Network n){notifyNet();syncInternetTime();}public void onLost(Network n){notifyNet();}public void onCapabilitiesChanged(Network n,NetworkCapabilities c){notifyNet();if(c.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED))syncInternetTime();}};try{cm.registerDefaultNetworkCallback(cb);}catch(Exception e){}webView.loadUrl("file:///android_asset/index.html");updateBadge();if(new AndroidStatus().hasInternet())syncInternetTime();}
 protected void onResume(){super.onResume();restorePersistentState();updateBadge();updateClock();if(new AndroidStatus().hasInternet())syncInternetTime();}protected void onDestroy(){savePersistentState();clockHandler.removeCallbacks(clockTick);try{cm.unregisterNetworkCallback(cb);}catch(Exception e){}super.onDestroy();}public void onBackPressed(){if(webView.canGoBack())webView.goBack();else super.onBackPressed();}
}
