package com.stevesuzon.carlplay;

import android.Manifest;import android.annotation.SuppressLint;import android.app.Activity;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.net.*;import android.net.Uri;import android.os.Bundle;import android.os.SystemClock;import android.os.Handler;import android.os.Looper;import android.provider.Settings;import android.view.*;import android.webkit.*;import android.widget.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.Locale;import java.net.HttpURLConnection;import java.net.URL;import java.text.SimpleDateFormat;import java.util.Date;import java.io.*;

public class MainActivity extends Activity{
 static final int LOCATION_REQUEST=1001;static final long DAY=86400000L,LICENSE_DAYS=0L,GRACE_DAYS=0L;static final String PREFS="carlplay_license_test_expired",SECRET="CP66-365-RENOUVELLEMENT-SUZON-2026",LIFE_SECRET="CP66-LIFETIME-CARPLAY-STEVE-2026",STATE_SECRET="CP66-STATE-CARPLAY-STEVE-2026";
 WebView webView;ConnectivityManager cm;ConnectivityManager.NetworkCallback cb;SharedPreferences prefs;TextView badge,network,clock;FrameLayout root;Handler clockHandler=new Handler(Looper.getMainLooper());
 Runnable clockTick=new Runnable(){public void run(){updateClock();clockHandler.postDelayed(this,1000);}};
 public class AndroidStatus{@JavascriptInterface public boolean hasInternet(){try{Network n=cm.getActiveNetwork();NetworkCapabilities c=n==null?null:cm.getNetworkCapabilities(n);return c!=null&&c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)&&c.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED);}catch(Exception e){return false;}}@JavascriptInterface public boolean licenseExpired(){return expired(now());}@JavascriptInterface public String licenseRequestCode(){return formatReq(requestCode());}@JavascriptInterface public String renewLicense(String code){return renew(code)?"OK":"ERREUR";}@JavascriptInterface public long licenseDaysLeft(){return isLifetime()?999999L:daysLeft(now());}@JavascriptInterface public boolean licenseLifetime(){return isLifetime();}}
 boolean isLifetime(){return prefs.getBoolean("lifetime",false);}String deviceId(){String id=Settings.Secure.getString(getContentResolver(),Settings.Secure.ANDROID_ID);return id==null?"unknown":id;}String hash(String v){try{MessageDigest m=MessageDigest.getInstance("SHA-256");byte[] b=m.digest(v.getBytes(StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.US,"%02x",x&255));return s.toString();}catch(Exception e){return"0000000000000000";}}
 long trustedClock(){long epoch=prefs.getLong("trusted_epoch",0L),elapsed=prefs.getLong("trusted_elapsed",0L);if(epoch<=0||elapsed<=0)return 0L;long d=SystemClock.elapsedRealtime()-elapsed;return d>=0?epoch+d:epoch;}long displayClockMillis(){long system=System.currentTimeMillis();long off=prefs.getLong("internet_offset",Long.MIN_VALUE);if(off!=Long.MIN_VALUE)return system+off;long trusted=trustedClock();return trusted>0?Math.max(system,trusted):system;}long now(){long system=System.currentTimeMillis(),last=prefs.getLong("last_seen",0L);long e=Math.max(last,system);prefs.edit().putLong("last_seen",e).apply();return e;}long start(){long s=prefs.getLong("license_start",0);if(s==0){s=System.currentTimeMillis();prefs.edit().putLong("license_start",s).apply();}return s;}
 void syncInternetTime(){}long daysLeft(long n){return 0;}long graceLeft(long n){return 0;}boolean expired(long n){return !isLifetime();}
 String requestCode(){int c=prefs.getInt("renewal_cycle",0);String h=hash(deviceId()+"|"+c+"|"+start());long n;try{n=Long.parseUnsignedLong(h.substring(0,12),16)%100000000L;}catch(Exception e){n=0;}return String.format(Locale.US,"%08d",n);}String formatReq(String s){return s.substring(0,2)+"."+s.substring(2,4)+"."+s.substring(4,6)+"."+s.substring(6,8);}String expected(){String h=hash(SECRET+"|"+requestCode());long n;try{n=Long.parseUnsignedLong(h.substring(0,12),16)%100000000L;}catch(Exception e){n=0;}return String.format(Locale.US,"%08d",n);}String expectedLifetime(){String h=hash(LIFE_SECRET+"|"+requestCode());long n;try{n=Long.parseUnsignedLong(h.substring(0,12),16)%100000000L;}catch(Exception e){n=0;}return String.format(Locale.US,"%08d",n);}
 boolean renew(String entered){String x=entered==null?"":entered.replaceAll("[^0-9]","");if(expectedLifetime().equals(x)){prefs.edit().putBoolean("lifetime",true).apply();runOnUiThread(()->updateBadge());return true;}if(!expected().equals(x))return false;int c=prefs.getInt("renewal_cycle",0)+1;prefs.edit().putInt("renewal_cycle",c).apply();runOnUiThread(()->Toast.makeText(this,"CODE 1 AN ACCEPTÉ — TEST RÉUSSI",Toast.LENGTH_LONG).show());return true;}
 void updateBadge(){if(badge==null)return;if(isLifetime()){badge.setText("LICENCE • À VIE");badge.setBackgroundColor(Color.argb(210,16,110,62));}else{badge.setText("ABONNEMENT EXPIRÉ — VERSION TEST");badge.setBackgroundColor(Color.argb(235,150,20,20));}updateNetwork();}void updateNetwork(){if(network==null)return;boolean ok=new AndroidStatus().hasInternet();network.setText(ok?"📶 CONNECTÉ":"📶 DÉCONNECTÉ");network.setTextColor(ok?Color.rgb(65,230,105):Color.rgb(255,75,75));network.setBackgroundColor(Color.argb(190,5,10,18));}void updateClock(){if(clock==null)return;clock.setText(new SimpleDateFormat("HH:mm",Locale.FRANCE).format(new Date(displayClockMillis())));}
 void makeTop(){int den=(int)getResources().getDisplayMetrics().density;int h=12*den,v=7*den,m=8*den;LinearLayout left=new LinearLayout(this);left.setOrientation(LinearLayout.HORIZONTAL);badge=new TextView(this);badge.setTextColor(Color.WHITE);badge.setTextSize(14);badge.setTypeface(Typeface.DEFAULT_BOLD);badge.setPadding(h,v,h,v);left.addView(badge);network=new TextView(this);network.setTextSize(12);network.setTypeface(Typeface.DEFAULT_BOLD);network.setPadding(10*den,v,10*den,v);left.addView(network);network.setOnClickListener(x->startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS)));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.LEFT);lp.setMargins(m,m,m,m);root.addView(left,lp);clock=new TextView(this);clock.setTextColor(Color.WHITE);clock.setTextSize(30);clock.setTypeface(Typeface.DEFAULT_BOLD);clock.setPadding(18*den,4*den,18*den,4*den);clock.setBackgroundColor(Color.argb(165,0,0,0));FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.CENTER_HORIZONTAL);root.addView(clock,cp);}
 void injectUi(WebView v){v.evaluateJavascript("(function(){var s=document.createElement('script');s.src='license-ui.js?'+Date.now();document.head.appendChild(s)})()",null);}
 @SuppressLint({"SetJavaScriptEnabled","AllowFileAccessFromFileURLs"}) public void onCreate(Bundle b){super.onCreate(b);getWindow().getDecorView().setSystemUiVisibility(5894);prefs=getSharedPreferences(PREFS,MODE_PRIVATE);start();cm=(ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);root=new FrameLayout(this);webView=new WebView(this);root.addView(webView,new FrameLayout.LayoutParams(-1,-1));makeTop();setContentView(root);clockHandler.post(clockTick);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setGeolocationEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setAllowFileAccessFromFileURLs(true);s.setAllowUniversalAccessFromFileURLs(true);webView.addJavascriptInterface(new AndroidStatus(),"AndroidStatus");webView.setWebChromeClient(new WebChromeClient());webView.setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String u){injectUi(v);}});webView.loadUrl("file:///android_asset/index.html");updateBadge();}
 protected void onResume(){super.onResume();updateBadge();updateClock();}protected void onDestroy(){clockHandler.removeCallbacks(clockTick);super.onDestroy();}public void onBackPressed(){if(webView.canGoBack())webView.goBack();else super.onBackPressed();}
}