package com.stevesuzon.carlplay;

import android.annotation.SuppressLint;import android.app.Activity;import android.content.*;import android.graphics.*;import android.net.*;import android.os.Bundle;import android.os.Handler;import android.os.Looper;import android.provider.Settings;import android.view.*;import android.webkit.*;import android.widget.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.Locale;import java.text.SimpleDateFormat;import java.util.Date;

public class MainActivity extends Activity{
 static final long DAY=86400000L,LICENSE_DAYS=365L,GRACE_DAYS=7L,LOCK_DAYS=15L;
 static final String PREFS="carplay_travaille_license",SECRET="CP66-365-RENOUVELLEMENT-SUZON-2026",LIFE_SECRET="CP66-LIFETIME-CARPLAY-STEVE-2026",UNLOCK_SECRET="CP66-UNLOCK-CARPLAY-STEVE-2026";
 WebView webView;ConnectivityManager cm;ConnectivityManager.NetworkCallback cb;SharedPreferences prefs;TextView badge,network,clock;FrameLayout root;Handler h=new Handler(Looper.getMainLooper());
 Runnable tick=new Runnable(){public void run(){updateClock();updateNetwork();updateBadge();h.postDelayed(this,1000);}};
 public class AndroidStatus{
  @JavascriptInterface public boolean hasInternet(){return internet();}
  @JavascriptInterface public boolean licenseExpired(){return expired(now());}
  @JavascriptInterface public String licenseRequestCode(){return formatReq(requestCode());}
  @JavascriptInterface public String renewLicense(String code){return renew(code);}
  @JavascriptInterface public long licenseDaysLeft(){return isLifetime()?999999L:daysLeft(now());}
  @JavascriptInterface public boolean licenseLifetime(){return isLifetime();}
  @JavascriptInterface public boolean licenseLocked(){return lockActive(now());}
  @JavascriptInterface public long lockDaysLeft(){return lockDays(now());}
  @JavascriptInterface public String unlockLicense(String code){return unlock(code);}
 }
 boolean internet(){try{
   if(cm==null)return false;
   Network active=cm.getActiveNetwork();
   if(active!=null){NetworkCapabilities c=cm.getNetworkCapabilities(active);if(c!=null&&(c.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)||c.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)||c.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET)||c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET)))return true;}
   Network[] all=cm.getAllNetworks();if(all!=null)for(Network n:all){NetworkCapabilities c=cm.getNetworkCapabilities(n);if(c!=null&&(c.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)||c.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)||c.hasTransport(NetworkCapabilities.TRANSPORT_ETHERNET))&&c.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET))return true;}
   NetworkInfo i=cm.getActiveNetworkInfo();return i!=null&&i.isConnected();
  }catch(Exception e){return false;}}
 boolean isLifetime(){return prefs.getBoolean("lifetime",false);}boolean activated(){return prefs.getBoolean("activated",false)||isLifetime();}
 String deviceId(){String id=Settings.Secure.getString(getContentResolver(),Settings.Secure.ANDROID_ID);return id==null?"unknown":id;}
 String hash(String v){try{MessageDigest m=MessageDigest.getInstance("SHA-256");byte[] b=m.digest(v.getBytes(StandardCharsets.UTF_8));StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.US,"%02x",x&255));return s.toString();}catch(Exception e){return"0000000000000000";}}
 long now(){long s=System.currentTimeMillis(),last=prefs.getLong("last_seen",0L),n=Math.max(s,last);prefs.edit().putLong("last_seen",n).apply();return n;}
 long start(){long s=prefs.getLong("license_start",0L);if(s==0L){s=System.currentTimeMillis();prefs.edit().putLong("license_start",s).apply();}return s;}
 long daysLeft(long n){if(!activated())return 0;if(isLifetime())return 999999L;long e=start()+LICENSE_DAYS*DAY;return n>=e?0:(long)Math.ceil((e-n)/(double)DAY);}
 long graceLeft(long n){if(!activated()||isLifetime())return 0;long e=start()+(LICENSE_DAYS+GRACE_DAYS)*DAY;return n>=e?0:(long)Math.ceil((e-n)/(double)DAY);}
 boolean expired(long n){if(isLifetime())return false;if(!activated())return true;return n>=start()+(LICENSE_DAYS+GRACE_DAYS)*DAY;}
 boolean lockActive(long n){long u=prefs.getLong("lock_until",0L);if(u<=0)return false;if(n>=u){prefs.edit().putLong("lock_until",0L).putInt("bad_codes",0).apply();return false;}return true;}
 long lockDays(long n){long u=prefs.getLong("lock_until",0L);if(u<=n)return 0;return (long)Math.ceil((u-n)/(double)DAY);}
 String requestCode(){int c=prefs.getInt("renewal_cycle",0);String x=hash(deviceId()+"|"+c+"|"+start());long n;try{n=Long.parseUnsignedLong(x.substring(0,12),16)%100000000L;}catch(Exception e){n=0;}return String.format(Locale.US,"%08d",n);}
 String formatReq(String s){return s.substring(0,2)+"."+s.substring(2,4)+"."+s.substring(4,6)+"."+s.substring(6,8);}
 String expected(String secret){String x=hash(secret+"|"+requestCode());long n;try{n=Long.parseUnsignedLong(x.substring(0,12),16)%100000000L;}catch(Exception e){n=0;}return String.format(Locale.US,"%08d",n);}
 String renew(String entered){long n=now();if(!expired(n))return "ACTIVE";if(lockActive(n))return "BLOQUE:"+lockDays(n);String x=entered==null?"":entered.replaceAll("[^0-9]","");if(expected(LIFE_SECRET).equals(x)){prefs.edit().putBoolean("lifetime",true).putBoolean("activated",true).putInt("bad_codes",0).putLong("lock_until",0L).apply();runOnUiThread(()->{updateBadge();webView.reload();});return "OK";}if(expected(SECRET).equals(x)){int c=prefs.getInt("renewal_cycle",0)+1;prefs.edit().putBoolean("lifetime",false).putBoolean("activated",true).putLong("license_start",n).putLong("last_seen",n).putInt("renewal_cycle",c).putInt("bad_codes",0).putLong("lock_until",0L).apply();runOnUiThread(()->{updateBadge();webView.reload();});return "OK";}int bad=prefs.getInt("bad_codes",0)+1;if(bad>=5){long until=n+LOCK_DAYS*DAY;prefs.edit().putInt("bad_codes",5).putLong("lock_until",until).apply();runOnUiThread(()->updateBadge());return "BLOQUE:15";}prefs.edit().putInt("bad_codes",bad).apply();if(bad==3)return "AVERT3";if(bad==4)return "AVERT4";return "ERREUR";}
 String unlock(String entered){long n=now();if(!lockActive(n))return "PAS_BLOQUE";String x=entered==null?"":entered.replaceAll("[^0-9]","");if(!expected(UNLOCK_SECRET).equals(x))return "ERREUR";prefs.edit().putInt("bad_codes",0).putLong("lock_until",0L).apply();runOnUiThread(()->{updateBadge();webView.reload();});return "OK";}
 void statusStyle(int textColor){if(badge==null)return;int d=(int)getResources().getDisplayMetrics().density;android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(Color.argb(235,5,10,18));g.setCornerRadius(18*d);g.setStroke(3*d,Color.rgb(243,155,25));badge.setBackground(g);badge.setTextColor(textColor);}
 void updateBadge(){if(badge==null)return;long n=now();if(isLifetime()){badge.setText("ACTIVÉE • À VIE");statusStyle(Color.rgb(70,235,120));}else if(expired(n)&&lockActive(n)){badge.setText("ABONNEMENT BLOQUÉ • "+lockDays(n)+" JOURS RESTANTS");statusStyle(Color.rgb(255,170,35));}else if(!activated()||expired(n)){badge.setText("APPLICATION DÉSACTIVÉE");statusStyle(Color.rgb(255,75,75));}else if(daysLeft(n)>0){badge.setText("ACTIVÉE • "+daysLeft(n)+" JOURS RESTANTS");statusStyle(Color.rgb(70,235,120));}else{badge.setText("GRÂCE • "+graceLeft(n)+" JOURS");statusStyle(Color.rgb(255,190,60));}}
 void updateNetwork(){if(network==null)return;boolean ok=internet();network.setText(ok?"📶 CONNECTÉ":"📶 DÉCONNECTÉ");network.setTextColor(ok?Color.rgb(70,235,120):Color.rgb(255,75,75));int d=(int)getResources().getDisplayMetrics().density;android.graphics.drawable.GradientDrawable g=new android.graphics.drawable.GradientDrawable();g.setColor(Color.argb(235,5,10,18));g.setCornerRadius(18*d);g.setStroke(3*d,ok?Color.rgb(70,235,120):Color.rgb(255,75,75));network.setBackground(g);}
 void updateClock(){if(clock!=null)clock.setText(new SimpleDateFormat("HH:mm",Locale.FRANCE).format(new Date()));}
 void makeTop(){int d=(int)getResources().getDisplayMetrics().density;
  badge=new TextView(this);badge.setTextSize(18);badge.setTypeface(Typeface.DEFAULT_BOLD);badge.setGravity(Gravity.CENTER);badge.setMinHeight(54*d);badge.setPadding(18*d,10*d,18*d,10*d);FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.LEFT);bp.setMargins(10*d,10*d,0,0);root.addView(badge,bp);
  LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(0,0,0,0);
  clock=new TextView(this);clock.setTextColor(Color.WHITE);clock.setTextSize(34);clock.setTypeface(Typeface.DEFAULT_BOLD);clock.setGravity(Gravity.CENTER);clock.setPadding(18*d,5*d,18*d,5*d);android.graphics.drawable.GradientDrawable cg=new android.graphics.drawable.GradientDrawable();cg.setColor(Color.argb(210,5,10,18));cg.setCornerRadius(18*d);cg.setStroke(2*d,Color.rgb(243,155,25));clock.setBackground(cg);top.addView(clock,new LinearLayout.LayoutParams(-2,58*d));
  network=new TextView(this);network.setTextSize(18);network.setTypeface(Typeface.DEFAULT_BOLD);network.setGravity(Gravity.CENTER);network.setMinHeight(58*d);network.setMinWidth(165*d);network.setPadding(16*d,10*d,16*d,10*d);LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(-2,58*d);np.setMargins(10*d,0,0,0);top.addView(network,np);network.setOnClickListener(v->{try{startActivity(new Intent(Settings.ACTION_WIFI_SETTINGS));}catch(Exception e){try{startActivity(new Intent(Settings.ACTION_WIRELESS_SETTINGS));}catch(Exception ignored){}}});
  FrameLayout.LayoutParams tp=new FrameLayout.LayoutParams(-2,-2,Gravity.TOP|Gravity.CENTER_HORIZONTAL);tp.setMargins(0,8*d,0,0);root.addView(top,tp);
 }
 void injectUi(WebView v){v.evaluateJavascript("(function(){var s=document.createElement('script');s.src='license-ui.js?'+Date.now();document.head.appendChild(s)})()",null);}
 @SuppressLint({"SetJavaScriptEnabled","AllowFileAccessFromFileURLs"}) public void onCreate(Bundle b){super.onCreate(b);getWindow().getDecorView().setSystemUiVisibility(5894);prefs=getSharedPreferences(PREFS,MODE_PRIVATE);start();cm=(ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);root=new FrameLayout(this);webView=new WebView(this);root.addView(webView,new FrameLayout.LayoutParams(-1,-1));makeTop();setContentView(root);h.post(tick);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setGeolocationEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setAllowFileAccessFromFileURLs(true);s.setAllowUniversalAccessFromFileURLs(true);webView.addJavascriptInterface(new AndroidStatus(),"AndroidStatus");webView.setWebChromeClient(new WebChromeClient());webView.setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String u){injectUi(v);}});cb=new ConnectivityManager.NetworkCallback(){public void onAvailable(Network n){runOnUiThread(()->updateNetwork());}public void onLost(Network n){runOnUiThread(()->updateNetwork());}public void onCapabilitiesChanged(Network n,NetworkCapabilities c){runOnUiThread(()->updateNetwork());}};try{cm.registerDefaultNetworkCallback(cb);}catch(Exception e){}webView.loadUrl("file:///android_asset/index.html");updateBadge();updateNetwork();}
 protected void onResume(){super.onResume();updateBadge();updateClock();updateNetwork();}protected void onDestroy(){h.removeCallbacks(tick);try{cm.unregisterNetworkCallback(cb);}catch(Exception e){}super.onDestroy();}public void onBackPressed(){if(webView.canGoBack())webView.goBack();else super.onBackPressed();}
}
