const assert=require('node:assert/strict');
const fs=require('node:fs');
require('../public/market-dedup-v511.js');
const {same,rows}=global.MarketDedupV511;
function row(name,day='samedi',address='Palaiseau',lat=null,lon=null,time='7h-13h'){return ['91','marche',name,'Palaiseau',day,time,'','',address,[],lat,lon];}
assert(same(row('Place des Causeuses'),row('Marché Causeuses')));
assert(same(row('Marché du Pileu alimentaire'),row('Marché couvert du Pileu')));
assert(!same(row('Marché de Lozère'),row('Marché du Pileu alimentaire')));
assert(!same(row('Marché de Lozère'),row('Marché de Lozère','mercredi')));
assert(same(row('Lozère','samedi','1 rue Collet, 91120 Palaiseau',48.71,2.23),row('Halle alimentaire','samedi','1 rue Collet Palaiseau',48.7101,2.23)));
assert(!same(row('Marché de Lozère','samedi','1 rue Collet'),row('Marché de Lozère','samedi','rue de Paris')));
assert(!same(row('Lozère','samedi','Palaiseau',48.71,2.23),row('Pileu','samedi','Palaiseau',48.71,2.23)));
assert(!same(row('Lozère','samedi','1 rue Collet',48.71,2.23),row('Halle','samedi','1 rue Collet',48.73,2.23)));
assert(!same(row('Lozère','samedi','1 rue Collet',null,null,'8h-13h'),row('Lozère','samedi','1 rue Collet',null,null,'17h-20h')));
assert(!same(row('Marché de Palaiseau'),row('Marché de Lozère')));
const original=[row('Place des Causeuses'),row('Marché Causeuses'),row('Marché Causeuses','mercredi'),row('Marché du Pileu alimentaire'),row('Marché de Lozère')];
const before=JSON.stringify(original);assert.equal(rows(original).length,4);assert.equal(JSON.stringify(original),before);assert.equal(rows(original)[0],original[0]);
assert(same(row('marché de janvry'),row('Marché Janvry')));
const bondoufleA=row('Marché Bondoufle','samedi','Bondoufle'),bondoufleB=row('Marché de Bondoufle','samedi','Centre commercial des Trois Parts, 91070, Bondoufle');bondoufleA[3]=bondoufleB[3]='Bondoufle';assert(same(bondoufleA,bondoufleB));
assert(!same(row('Marché Palaiseau','samedi','rue Collet'),row('Marché de Palaiseau','samedi','place de la Victoire')));
assert(!same(row('Marché Palaiseau','samedi','Palaiseau',48.71,2.23),row('Marché de Palaiseau','samedi','Palaiseau',48.73,2.23)));
const janvry=JSON.parse(fs.readFileSync(require('node:path').join(__dirname,'../public/market-chunks/fr/91/samedi.json'))).filter(r=>r[3]==='Janvry');
assert.equal(rows(janvry).length,1);
const restoredKey=global.MarketDedupV511.key('fr',original[1]);
global.MarketDedupV511.setDecision(restoredKey,'restored');assert.equal(rows(original).length,5);
global.MarketDedupV511.setDecision(restoredKey,'deleted');assert.equal(rows(original).length,4);
global.MarketDedupV511.setDecision(restoredKey,'pending');assert.equal(rows(original).length,4);
console.log('Generic names, Janvry, Bondoufle, distinct sites and days passed');
const path=require('node:path'),dataRoot=path.join(__dirname,'../public/market-chunks');let files=0,removed=0;
function checkDirectory(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory()){checkDirectory(file);continue;}if(!file.endsWith('.json'))continue;const input=JSON.parse(fs.readFileSync(file)),output=rows(input);assert.deepEqual(rows(output),output);assert(output.every(r=>input.includes(r)));files++;removed+=input.length-output.length;}}
checkDirectory(dataRoot);console.log(files+' day/area datasets checked; '+removed+' duplicate entries grouped');
const page=fs.readFileSync(require('node:path').join(__dirname,'../public/nearby-markets.html'),'utf8');
for(const match of page.matchAll(/<script>([\s\S]*?)<\/script>/g))new (require('node:vm').Script)(match[1]);
console.log('Nearby page inline script syntax valid');
