from pathlib import Path
import re

A=Path('app/src/main/assets')
A.mkdir(parents=True,exist_ok=True)

def extract(src,name):
    t=Path(src).read_text(encoding='utf-8',errors='ignore')
    m=re.search(r'const\s+'+re.escape(name)+r'\s*=\s*(\[.*?\]);',t,re.S)
    if not m:
        raise SystemExit('Impossible de trouver '+name+' dans '+src)
    return m.group(1)

TEMPLATE=r'''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>__TITLE__</title><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Arial,sans-serif;color:#fff;background:#07101d}body{min-height:100vh;position:relative;overflow-x:hidden}.route66bg{position:fixed;left:0;top:0;width:100vw;height:100vh;object-fit:cover;object-position:center center;z-index:-2}.shade{min-height:100vh;background:rgba(2,8,18,.48);padding:12px}.app{width:min(1180px,98vw);margin:auto}h1{text-align:center;font-size:44px;margin:8px 0 18px;text-shadow:0 3px 10px #000}.picker{background:rgba(8,19,38,.92);padding:18px;border-radius:24px}.label{font-size:22px;font-weight:900;margin:0 0 10px}select{width:100%;height:88px;border:4px solid #62d8ff;border-radius:22px;background:#0a2d55;color:#fff;font-size:30px;font-weight:900;padding:0 18px}#confirm{display:block;width:82%;height:92px;margin:20px auto 0;border:4px solid #777;border-radius:26px;background:#555;color:#aaa;font-size:34px;font-weight:950}#confirm.ready{background:linear-gradient(135deg,#05aaff,#1739db);border-color:#62d8ff;color:#fff}.results{display:none;margin-top:18px}.days{position:sticky;top:0;z-index:10;display:flex;gap:10px;overflow-x:auto;white-space:nowrap;padding:12px 4px;background:rgba(4,13,28,.94);border-radius:18px}.day{flex:0 0 auto;min-width:112px;height:56px;border:2px solid #62d8ff;border-radius:999px;background:#132a48;color:#fff;font-size:20px;font-weight:900}.day.active{background:#087ee5}.heading{font-size:28px;font-weight:900;margin:16px 4px}.cards{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.card{background:rgba(8,19,38,.94);padding:18px;border:1px solid #ffffff35;border-radius:20px}.name{font-size:26px;font-weight:950}.meta{margin-top:9px;font-size:18px;line-height:1.35}.weather{margin-top:16px;padding:12px;border-radius:14px;background:rgba(2,12,25,.72);font-size:17px}.actions{display:flex;gap:12px;margin-top:16px}.actions button{flex:1;height:58px;border:0;border-radius:15px;color:#fff;font-size:17px;font-weight:900}.nav{background:#087ee5}.verify{background:#f39b19}.modalBack{display:none;position:fixed;inset:0;z-index:100;background:rgba(0,0,0,.72);padding:5vh 4vw}.modal{max-width:680px;margin:auto;background:#10233a;border:3px solid #62d8ff;border-radius:22px;padding:18px}.modal input,.modal select,.modal textarea{width:100%;min-height:50px;margin:6px 0 12px;border-radius:12px;border:1px solid #ffffff55;background:#081727;color:#fff;font-size:18px;padding:9px}.modalBtns{display:flex;gap:10px}.modalBtns button{flex:1;height:54px;border:0;border-radius:12px;color:#fff;font-weight:900;font-size:18px}@media(max-width:760px){h1{font-size:32px}select{font-size:23px;height:76px}#confirm{width:92%;height:82px;font-size:29px}.cards{grid-template-columns:1fr}.actions{flex-direction:column}}
</style></head><body><img class="route66bg" src="route66-bg.jpg" alt=""><div class="shade"><main class="app"><h1>__TITLE__</h1><section class="picker"><div class="label">CHOISIR SON __AREAWORD__</div><select id="areaSelect"><option value="">— APPUYEZ ICI —</option></select><button id="confirm" disabled>CONFIRMER</button></section><section id="results" class="results"><div id="days" class="days"></div><div id="heading" class="heading"></div><div id="cards" class="cards"></div></section></main></div><div id="modalBack" class="modalBack"><div class="modal"><h2>VÉRIFIER CE MARCHÉ</h2><div id="verifyName"></div><label>Horaire</label><input id="vTime"><label>Nombre de commerçants</label><input id="vCount"><label>Tirage au sort</label><select id="vDraw"><option value="">À préciser</option><option>Oui</option><option>Non</option></select><label>Remarque</label><textarea id="vNote"></textarea><div class="modalBtns"><button id="cancel" style="background:#555">ANNULER</button><button id="save" style="background:#087ee5">ENREGISTRER</button></div></div></div><script>
var country='__COUNTRY__';var areas=__AREAS__;var data=__DATA__;var selected=null;var currentDay='lundi';var verifyIndex=-1;var dayNames={lundi:'LUN',mardi:'MAR',mercredi:'MER',jeudi:'JEU',vendredi:'VEN',samedi:'SAM',dimanche:'DIM'};
function el(id){return document.getElementById(id)}
function esc(s){s=String(s==null?'':s);return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;')}
function label(a){return country==='fr'?(a[0]+' — '+a[1]):a[1]}
function initAreas(){var s=el('areaSelect');var i,o;for(i=0;i<areas.length;i++){o=document.createElement('option');o.value=String(i);o.text=label(areas[i]);s.appendChild(o)}s.onchange=function(){if(this.value===''){selected=null;el('confirm').disabled=true;el('confirm').className='';return}selected=areas[parseInt(this.value,10)];el('confirm').disabled=false;el('confirm').className='ready'}}
function buildDays(){var html='',k;for(k in dayNames){if(dayNames.hasOwnProperty(k)){html+='<button class="day '+(k===currentDay?'active':'')+'" data-day="'+k+'">'+dayNames[k]+'</button>'}}el('days').innerHTML=html;var b=document.getElementsByClassName('day');var i;for(i=0;i<b.length;i++){b[i].onclick=function(){currentDay=this.getAttribute('data-day');buildDays();render()}}}
function rows(){var out=[],i,r;if(!selected)return out;for(i=0;i<data.length;i++){r=data[i];if(r[0]===selected[0]&&String(r[4]||'').toLowerCase()===currentDay)out.push(r)}return out}
function key(r){return 'marketVerify:'+country+':'+r.slice(0,6).join('|')}
function saved(r){try{var x=localStorage.getItem(key(r));return x?JSON.parse(x):null}catch(e){return null}}
function render(){var rs=rows();var html='';var i,r,s,name,place,time,count,draw;el('heading').innerHTML=esc(label(selected))+' — '+dayNames[currentDay];for(i=0;i<rs.length;i++){r=rs[i];s=saved(r)||{};name=r[2]||r[1]||'Marché';place=r[3]||'À préciser';time=s.time||r[5]||'Horaire à vérifier';count=s.count||r[7]||'À vérifier';draw=s.draw||'À vérifier';html+='<article class="card"><div class="name">'+esc(name)+'</div><div class="meta">📍 '+esc(place)+'</div><div class="meta">🕒 '+esc(time)+'</div><div class="meta">👥 Commerçants : '+esc(count)+'</div><div class="meta">🎲 Tirage : '+esc(draw)+'</div><div class="weather"><b>🌤️ Météo 07h00–13h30</b><br>Prévision disponible avec la connexion de l’autoradio.</div><div class="actions"><button class="nav" onclick="goMarket('+i+')">ALLER AU MARCHÉ</button><button class="verify" onclick="openVerify('+i+')">VÉRIFIER</button></div></article>'}if(!html)html='<article class="card">Aucun marché enregistré pour ce jour.</article>';el('cards').innerHTML=html}
el('confirm').onclick=function(){if(!selected)return;buildDays();render();el('results').style.display='block';setTimeout(function(){el('results').scrollIntoView(true)},50)}
function goMarket(i){var r=rows()[i];var q=encodeURIComponent((r[2]||'')+' '+(r[3]||''));window.location.href='https://www.google.com/maps/search/?api=1&query='+q}
function openVerify(i){var r=rows()[i];var s=saved(r)||{};verifyIndex=i;el('verifyName').innerHTML=esc((r[2]||'Marché')+' — '+(r[3]||''));el('vTime').value=s.time||r[5]||'';el('vCount').value=s.count||r[7]||'';el('vDraw').value=s.draw||'';el('vNote').value=s.note||'';el('modalBack').style.display='block'}
el('cancel').onclick=function(){el('modalBack').style.display='none'};el('save').onclick=function(){var r=rows()[verifyIndex];try{localStorage.setItem(key(r),JSON.stringify({time:el('vTime').value,count:el('vCount').value,draw:el('vDraw').value,note:el('vNote').value}))}catch(e){}el('modalBack').style.display='none';render()};
initAreas();
</script></body></html>'''

def page(country,title,word,areas,data):
    return TEMPLATE.replace('__COUNTRY__',country).replace('__TITLE__',title).replace('__AREAWORD__',word).replace('__AREAS__',areas).replace('__DATA__',data)

fr_areas=extract('/tmp/france-source.html','departments')
fr_data=extract('/tmp/france-source.html','data')
be_areas=extract('/tmp/belgique-source.html','regions')
be_data=extract('/tmp/belgique-source.html','data')
(A/'marches.html').write_text(page('fr','MARCHÉS DE FRANCE','DÉPARTEMENT',fr_areas,fr_data),encoding='utf-8')
(A/'belgique-marches.html').write_text(page('be','MARCHÉS DE BELGIQUE','PROVINCE / RÉGION',be_areas,be_data),encoding='utf-8')
