from pathlib import Path
import re

A=Path('app/src/main/assets')
A.mkdir(parents=True,exist_ok=True)

def extract(src,name):
    t=Path(src).read_text(encoding='utf-8',errors='ignore')
    m=re.search(r'const\s+'+re.escape(name)+r'\s*=\s*(\[.*?\]);',t,re.S)
    if not m: raise SystemExit(f'Impossible de trouver {name} dans {src}')
    return m.group(1)

# Générateur autonome : les anciennes pages marchés ne sont jamais réutilisées comme interface.
# Seules leurs données (departments/regions + data) sont extraites pendant la compilation.
TEMPLATE='''<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>__TITLE__</title><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Arial,sans-serif;color:#fff;background:#07101d url('route66-bg.jpg') center/cover fixed no-repeat}.shade{min-height:100vh;background:#02081273;padding:12px}.app{width:min(1120px,97vw);margin:auto}h1{text-align:center;font-size:clamp(30px,5vw,54px);text-shadow:0 3px 10px #000}.picker,.card{background:#081326e8;border-radius:22px}.picker{padding:14px}button{font-family:inherit;touch-action:manipulation}#choose,#confirm{width:100%;min-height:74px;border-radius:22px;font-size:clamp(20px,3vw,30px);font-weight:900;color:#fff}#choose{border:3px solid #62d8ff;background:linear-gradient(135deg,#05aaff,#1739db);display:flex;justify-content:space-between;align-items:center;padding:0 22px}#confirm{margin-top:12px;border:2px solid #777;background:#555;color:#aaa}#confirm.ready{background:linear-gradient(135deg,#05aaff,#1739db);border-color:#62d8ff;color:#fff}#panel{display:none;position:fixed;inset:3vh 2vw;z-index:100;background:#10233afa;border:3px solid #62d8ff;border-radius:24px;padding:12px;overflow:auto}#panel.open{display:block}#close{position:sticky;top:0;width:100%;height:56px;border:0;border-radius:15px;background:#d84343;color:#fff;font-weight:900;font-size:18px}.area{width:100%;min-height:60px;margin:5px 0;border:1px solid #ffffff55;border-radius:16px;background:#1d3049;color:#fff;font-size:20px;font-weight:800;text-align:left;padding:10px 18px}#results{display:none;margin-top:14px}.days{position:sticky;top:0;z-index:20;display:flex;gap:9px;overflow-x:auto;white-space:nowrap;padding:10px 4px;background:#040d1ce8;border-radius:18px}.day{flex:0 0 auto;min-width:108px;height:52px;border:2px solid #62d8ff;border-radius:999px;background:#132a48;color:#fff;font-size:18px;font-weight:900}.day.active{background:#087ee5}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:12px}.card{padding:16px;border:1px solid #ffffff35}.name{font-size:24px;font-weight:900}.meta{margin-top:8px;font-size:17px}.weather{margin-top:16px;padding:10px;border-radius:14px;background:#020c19a8}.actions{display:flex;gap:10px;margin-top:14px}.actions button{flex:1;min-height:54px;border:0;border-radius:15px;color:#fff;font-size:17px;font-weight:900}.nav{background:#087ee5}.verify{background:#f39b19}dialog{width:min(650px,92vw);border:2px solid #62d8ff;border-radius:20px;background:#10233a;color:#fff;padding:18px}dialog input,dialog select,dialog textarea{width:100%;min-height:46px;margin:5px 0 10px;border-radius:10px;background:#081727;color:#fff;border:1px solid #ffffff55;padding:8px}.modal{display:flex;gap:10px}.modal button{flex:1;min-height:50px;border:0;border-radius:12px;color:#fff;font-weight:900}@media(max-width:700px){.cards{grid-template-columns:1fr}.actions{flex-direction:column}}
</style></head><body><div class="shade"><main class="app"><h1>__TITLE__</h1><section class="picker"><button id="choose"><span>CHOISIR SON __AREAWORD__</span><span>▼</span></button><button id="confirm" disabled>CONFIRMER</button></section><section id="results"><div id="days" class="days"></div><h2 id="heading"></h2><div id="cards" class="cards"></div></section></main></div><div id="panel"><button id="close">FERMER</button><div id="areas"></div></div><dialog id="dlg"><h2>VÉRIFIER CE MARCHÉ</h2><div id="vn"></div><label>Horaire</label><input id="vt"><label>Nombre de commerçants</label><input id="vc"><label>Tirage au sort</label><select id="vd"><option value="">À préciser</option><option>Oui</option><option>Non</option></select><label>Remarque</label><textarea id="vnote"></textarea><div class="modal"><button style="background:#555" id="cancel">ANNULER</button><button style="background:#087ee5" id="save">ENREGISTRER</button></div></dialog><script>
const country='__COUNTRY__',areas=__AREAS__,data=__DATA__;const names={lundi:'LUN',mardi:'MAR',mercredi:'MER',jeudi:'JEU',vendredi:'VEN',samedi:'SAM',dimanche:'DIM'};let selected=null,day='lundi',vi=0;const $=x=>document.getElementById(x);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const label=a=>country==='fr'?a[0]+' — '+a[1]:a[1];
function populate(){$('areas').innerHTML=areas.map((a,i)=>`<button class="area" data-i="${i}">${esc(label(a))}</button>`).join('');document.querySelectorAll('.area').forEach(b=>b.onclick=()=>{selected=areas[+b.dataset.i];$('choose').firstElementChild.textContent=label(selected);$('confirm').disabled=false;$('confirm').classList.add('ready');$('panel').classList.remove('open')})}$('choose').onclick=()=>$('panel').classList.add('open');$('close').onclick=()=>$('panel').classList.remove('open');
function days(){$('days').innerHTML=Object.entries(names).map(([k,v])=>`<button class="day ${k===day?'active':''}" data-d="${k}">${v}</button>`).join('');document.querySelectorAll('.day').forEach(b=>b.onclick=()=>{day=b.dataset.d;days();render()})}function rows(){return selected?data.filter(r=>r[0]===selected[0]&&String(r[4]||'').toLowerCase()===day):[]}function key(r){return 'marketVerify:'+country+':'+r.slice(0,6).join('|')}function saved(r){try{return JSON.parse(localStorage.getItem(key(r))||'null')}catch(e){return null}}
function render(){const rs=rows();$('heading').textContent=label(selected)+' — '+names[day];$('cards').innerHTML=rs.length?rs.map((r,i)=>{const s=saved(r)||{};return `<article class="card"><div class="name">${esc(r[2]||r[1]||'Marché')}</div><div class="meta">📍 ${esc(r[3]||'À préciser')}</div><div class="meta">🕒 ${esc(s.time||r[5]||'Horaire à vérifier')}</div><div class="meta">👥 Commerçants : ${esc(s.count||r[7]||'À vérifier')}</div><div class="meta">🎲 Tirage : ${esc(s.draw||'À vérifier')}</div><div class="weather"><b>🌤️ Météo 07h00–13h30</b><br>Prévision disponible avec la connexion de l’autoradio.</div><div class="actions"><button class="nav" onclick="nav(${i})">ALLER AU MARCHÉ</button><button class="verify" onclick="verify(${i})">VÉRIFIER</button></div></article>`}).join(''):'<article class="card">Aucun marché enregistré pour ce jour.</article>'}$('confirm').onclick=()=>{if(!selected)return;days();render();$('results').style.display='block';setTimeout(()=>$('results').scrollIntoView({behavior:'smooth'}),60)};function nav(i){const r=rows()[i];location.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent((r[2]||'')+' '+(r[3]||''))}function verify(i){vi=i;const r=rows()[i],s=saved(r)||{};$('vn').textContent=(r[2]||'Marché')+' — '+(r[3]||'');$('vt').value=s.time||r[5]||'';$('vc').value=s.count||r[7]||'';$('vd').value=s.draw||'';$('vnote').value=s.note||'';$('dlg').showModal()}$('cancel').onclick=()=>$('dlg').close();$('save').onclick=()=>{const r=rows()[vi];localStorage.setItem(key(r),JSON.stringify({time:$('vt').value,count:$('vc').value,draw:$('vd').value,note:$('vnote').value}));$('dlg').close();render()};populate();
</script></body></html>'''

def page(country,title,word,areas,data):
    return TEMPLATE.replace('__COUNTRY__',country).replace('__TITLE__',title).replace('__AREAWORD__',word).replace('__AREAS__',areas).replace('__DATA__',data)

fr_areas=extract('/tmp/france-source.html','departments');fr_data=extract('/tmp/france-source.html','data')
be_areas=extract('/tmp/belgique-source.html','regions');be_data=extract('/tmp/belgique-source.html','data')
(A/'marches.html').write_text(page('fr','MARCHÉS DE FRANCE','DÉPARTEMENT',fr_areas,fr_data),encoding='utf-8')
(A/'belgique-marches.html').write_text(page('be','MARCHÉS DE BELGIQUE','PROVINCE / RÉGION',be_areas,be_data),encoding='utf-8')
