(function(){
const deps=`01|Ain,02|Aisne,03|Allier,04|Alpes-de-Haute-Provence,05|Hautes-Alpes,06|Alpes-Maritimes,07|Ardèche,08|Ardennes,09|Ariège,10|Aube,11|Aude,12|Aveyron,13|Bouches-du-Rhône,14|Calvados,15|Cantal,16|Charente,17|Charente-Maritime,18|Cher,19|Corrèze,2A|Corse-du-Sud,2B|Haute-Corse,21|Côte-d’Or,22|Côtes-d’Armor,23|Creuse,24|Dordogne,25|Doubs,26|Drôme,27|Eure,28|Eure-et-Loir,29|Finistère,30|Gard,31|Haute-Garonne,32|Gers,33|Gironde,34|Hérault,35|Ille-et-Vilaine,36|Indre,37|Indre-et-Loire,38|Isère,39|Jura,40|Landes,41|Loir-et-Cher,42|Loire,43|Haute-Loire,44|Loire-Atlantique,45|Loiret,46|Lot,47|Lot-et-Garonne,48|Lozère,49|Maine-et-Loire,50|Manche,51|Marne,52|Haute-Marne,53|Mayenne,54|Meurthe-et-Moselle,55|Meuse,56|Morbihan,57|Moselle,58|Nièvre,59|Nord,60|Oise,61|Orne,62|Pas-de-Calais,63|Puy-de-Dôme,64|Pyrénées-Atlantiques,65|Hautes-Pyrénées,66|Pyrénées-Orientales,67|Bas-Rhin,68|Haut-Rhin,69|Rhône,70|Haute-Saône,71|Saône-et-Loire,72|Sarthe,73|Savoie,74|Haute-Savoie,75|Paris,76|Seine-Maritime,77|Seine-et-Marne,78|Yvelines,79|Deux-Sèvres,80|Somme,81|Tarn,82|Tarn-et-Garonne,83|Var,84|Vaucluse,85|Vendée,86|Vienne,87|Haute-Vienne,88|Vosges,89|Yonne,90|Territoire de Belfort,91|Essonne,92|Hauts-de-Seine,93|Seine-Saint-Denis,94|Val-de-Marne,95|Val-d’Oise`.split(',').map(x=>x.split('|'));
function css(){if(document.getElementById('apk-market-ui-css'))return;const s=document.createElement('style');s.id='apk-market-ui-css';s.textContent=`#apkDepartmentWrap{position:sticky;top:0;z-index:99990;width:min(960px,99%);margin:0 auto 10px;padding:8px;background:rgba(20,28,43,.74);backdrop-filter:blur(8px);border-radius:0 0 22px 22px}#apkDepartmentButton{width:100%;min-height:86px;border:3px solid #65d2ff;border-radius:26px;background:linear-gradient(135deg,#05aaff,#1934d7);color:#fff;font-size:30px;font-weight:950;box-shadow:0 8px 24px #0008;text-align:left;padding:0 26px;display:flex;align-items:center;justify-content:space-between}#apkDepartmentPanel{display:none;position:fixed;left:1.5vw;right:1.5vw;top:88px;bottom:0;z-index:100000;background:rgba(21,47,66,.97);border:3px solid #65d2ff;border-radius:24px 24px 0 0;box-shadow:0 -8px 30px #000b;overflow-y:auto;-webkit-overflow-scrolling:touch;padding:12px}#apkDepartmentPanel.open{display:block}.apkDepRow{width:100%;min-height:66px;margin:6px 0;border:1px solid #ffffff35;border-radius:18px;background:linear-gradient(135deg,#263650,#1b2638);color:#fff;font-size:22px;font-weight:900;text-align:left;padding:12px 18px}#apkDepartmentClose{position:sticky;top:0;width:100%;min-height:58px;margin-bottom:8px;border:0;border-radius:16px;background:#d34343;color:#fff;font-size:20px;font-weight:900;z-index:2}.weather,.meteo,[class*="weather"],[class*="meteo"]{margin-top:24px!important}`;document.head.appendChild(s)}
function hideJunk(){document.querySelectorAll('body *').forEach(el=>{const t=(el.innerText||'').trim().toLowerCase();if(t.length&&t.length<350&&(t.includes('article de travail')||t.includes('ce site ne vous convient pas')||t.includes('essayez l’autre')||t.includes("essayez l'autre")||(t.includes('vérification')&&t.includes('20'))||(t.includes('verification')&&t.includes('20'))||(t.includes('envoy')&&t.includes('fichier'))||t==='pk'))el.style.display='none'})}
function revealDays(){document.querySelectorAll('#days,.days,#jours,.jours,[data-view="days"],[class*="day-list"],[class*="jours"],#list').forEach(e=>{e.style.setProperty('display','block','important');e.style.removeProperty('visibility');e.style.removeProperty('opacity')})}
function clickOriginalDepartment(code,name){
  const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,'');
  const targets=[code,name,code+' '+name].map(norm);
  const all=[...document.querySelectorAll('button,a,[role="button"],[data-dep],[data-departement],[data-department],option,li,div')];
  let candidate=null;
  for(const el of all){
    if(el.closest && el.closest('#apkDepartmentWrap')) continue;
    const vals=[el.textContent,el.getAttribute&&el.getAttribute('data-dep'),el.getAttribute&&el.getAttribute('data-departement'),el.getAttribute&&el.getAttribute('data-department'),el.value].map(norm);
    if(vals.some(v=>v===norm(code)||v===norm(name)||v===norm(code+name)||v.startsWith(norm(code+name)))){candidate=el;break;}
  }
  if(candidate){
    if(candidate.tagName==='OPTION'&&candidate.parentElement){candidate.selected=true;candidate.parentElement.dispatchEvent(new Event('change',{bubbles:true}));return true;}
    candidate.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}));
    if(typeof candidate.click==='function')candidate.click();
    return true;
  }
  const selects=[...document.querySelectorAll('select')];
  for(const sel of selects){
    const opt=[...sel.options].find(o=>{const v=norm(o.value),t=norm(o.textContent);return v===norm(code)||t.includes(norm(name))||t.startsWith(norm(code+name));});
    if(opt){sel.value=opt.value;sel.dispatchEvent(new Event('change',{bubbles:true}));return true;}
  }
  const inputs=[...document.querySelectorAll('input[type="search"],input[type="text"]')];
  for(const inp of inputs){inp.value=code+' '+name;inp.dispatchEvent(new Event('input',{bubbles:true}));inp.dispatchEvent(new Event('change',{bubbles:true}));}
  return false;
}
function goToDays(){setTimeout(()=>{revealDays();hideJunk();const sels=['#days','.days','#jours','.jours','[data-view="days"]','[class*="day-list"]','[class*="jours"]','#list'];for(const sel of sels){const e=document.querySelector(sel);if(e&&e.offsetParent!==null){e.scrollIntoView({behavior:'smooth',block:'start'});return}}},350)}
function choose(code,name,panel,btn){panel.classList.remove('open');document.body.style.overflow='';btn.childNodes[0].nodeValue=code+' — '+name+'  ';let ok=false;try{ok=clickOriginalDepartment(code,name)}catch(e){}if(!ok){try{if(typeof window.selectDep==='function'){window.selectDep(code);ok=true}}catch(e){}}setTimeout(()=>{revealDays();goToDays()},120)}
function install(){css();if(document.getElementById('apkDepartmentWrap'))return true;const host=document.getElementById('deps')||document.body;if(!host)return false;const wrap=document.createElement('div');wrap.id='apkDepartmentWrap';const btn=document.createElement('button');btn.id='apkDepartmentButton';btn.type='button';btn.appendChild(document.createTextNode('CHOISIR SON DÉPARTEMENT  '));const a=document.createElement('span');a.textContent='▼';btn.appendChild(a);const panel=document.createElement('div');panel.id='apkDepartmentPanel';const close=document.createElement('button');close.id='apkDepartmentClose';close.type='button';close.textContent='FERMER';close.onclick=()=>{panel.classList.remove('open');document.body.style.overflow=''};panel.appendChild(close);deps.forEach(d=>{const b=document.createElement('button');b.className='apkDepRow';b.type='button';b.textContent=d[0]+' — '+d[1];b.onclick=()=>choose(d[0],d[1],panel,btn);panel.appendChild(b)});btn.onclick=()=>{panel.classList.add('open');document.body.style.overflow='hidden'};wrap.append(btn,panel);host.insertBefore(wrap,host.firstChild);hideJunk();return true}
let n=0;function boot(){n++;if(!install()&&n<50)setTimeout(boot,120)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(hideJunk,400);setInterval(hideJunk,2500)
})();