plugins {
    id 'com.android.application'
}

android {
    namespace 'fr.suzon.couteausuisse.autoradio'
    compileSdk 35

    defaultConfig {
        applicationId 'fr.suzon.couteausuisse.autoradio'
        minSdk 21
        targetSdk 35
        versionCode 371
        versionName 'V371-Autoradio'
    }

    buildTypes {
        debug {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}
